version: '3.8'

services:
  hopbilet:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor 
      - ./database:/var/www/html/database
      
    restart: unless-stopped